version: "3.7"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CACHE_HOST=redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
